version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore source/ILMerge.Fody.sln
build:
  project: source/ILMerge.Fody.sln
  verbosity: minimal